config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only:[:new, :edit]
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def new
    @book = current_user.books.new
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @books = Book.all.order(created_at: :DESC)
  end

  def show
    if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rating).round(2)
    end
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :book_img)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

    def find_book
      @book = Book.find(params[:book_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_review
      @review = Review.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f|%>
  <%= f.file_field :book_img%>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<div class="row">
  <% @books.each do |book|%>
      <div class="col-md-3">
        <a href="/books/<%= book.id%>">
          <%= image_tag book.book_img.url(:book_index), class:"book" %>
        </a>
      </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show), class: "bookshow" %>
    <div style="margin-left:5px;">
      <% if user_signed_in? %>
        <div class="btn-group">
      <% if @book.user == current_user %>
          <%= link_to "Edit", edit_book_path(@book), class:"btn btn-default" %>
          <%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-default" %>
      <% end %>
      <% end %>
          <%= link_to "Back", root_path, class:"btn btn-default" %>
        </div>
    </div>
  </div>
  <div class="col-md-8">
    <h1><%= @book.title %></h1>
    <h3>By <%= @book.author %></h3>
    <div>
      <div style="float:left;" class="average-review-rating" data-score=<%= @average_review%>> by <%= @book.reviews.size %> reviews: </div>
      <div style="float:left; margin-left:50px;">
        <%= link_to "Add Review", new_book_review_path(@book) %>
      </div>
    </div>
    <div style="clear:both;"></div>
    <h4><%= simple_format(@book.description) %></h4>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-8">
    <%= render @book.reviews %>
  </div>
</div>

<script>
  $('.review-rating').raty({
    cancel: true,
    readOnly:true,
    size:24,
    score:function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  })
</script>

<script>
  $('.average-review-rating').raty({
    cancel: true,
    readOnly:true,
    size:24,
    path: '/assets/',
    score: function(){
      return $(this).attr('data-score');
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">

      <div class="container" id="nb1">

        <div class="navbar-header">
          <%= link_to image_tag('logo.png'), url_for(root_path), class: "navbar-brand", id:"logo" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li><%= link_to "Add Book", new_book_path, class:"btn btn-sm btn-default"%></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-sm btn-default" %></li>
          <% else %>
              <li><%= link_to "Log In", new_user_session_path, class:"btn btn-sm btn-default" %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, class:"btn btn-sm btn-default" %></li>
          <% end %>
        </ul>
      </div>

    </nav>
    <div class="container" style="margin-top: 5%;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f|%>
  <div id="rating-form">
      <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path:'/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p>
  <%= review.comment %>
</p>
<% if review.user == current_user %>
  <%= link_to "Edit", edit_book_review_path(@book, review) %>
  <%= link_to "Delete", book_review_path(@book, review), method: :delete %>
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit Review </h1>
<%= simple_form_for([@book, @review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add New Comment</h1>
<%= render 'form' %>